[workspace]
resolver = "2"
members = [
    "crates/orlando-core",
    "crates/orlando-runtime",
    "crates/orlando-persistence",
    "crates/orlando-timers",
    "crates/orlando-macros",
    "crates/orlando-cluster",
    "crates/orlando-client",
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
dashmap = "6"
async-trait = "0.1"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
anyhow = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1"
tonic = { version = "0.12", features = ["tls"] }
arc-swap = "1"
prost = "0.13"
metrics = "0.24"
fred = { version = "10", features = ["i-scripts", "i-hashes"] }
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1"
